
package com.training;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WetherServiceImplService", targetNamespace = "http://interfaces.training.com/", wsdlLocation = "http://localhost:5050/weather?wsdl")
public class WetherServiceImplService
    extends Service
{

    private final static URL WETHERSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WETHERSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName WETHERSERVICEIMPLSERVICE_QNAME = new QName("http://interfaces.training.com/", "WetherServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5050/weather?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WETHERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        WETHERSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public WetherServiceImplService() {
        super(__getWsdlLocation(), WETHERSERVICEIMPLSERVICE_QNAME);
    }

    public WetherServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WETHERSERVICEIMPLSERVICE_QNAME, features);
    }

    public WetherServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, WETHERSERVICEIMPLSERVICE_QNAME);
    }

    public WetherServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WETHERSERVICEIMPLSERVICE_QNAME, features);
    }

    public WetherServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WetherServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WeatherService
     */
    @WebEndpoint(name = "WetherServiceImplPort")
    public WeatherService getWetherServiceImplPort() {
        return super.getPort(new QName("http://interfaces.training.com/", "WetherServiceImplPort"), WeatherService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherService
     */
    @WebEndpoint(name = "WetherServiceImplPort")
    public WeatherService getWetherServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://interfaces.training.com/", "WetherServiceImplPort"), WeatherService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WETHERSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw WETHERSERVICEIMPLSERVICE_EXCEPTION;
        }
        return WETHERSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
