server:
  port: 7080
 
spring:
  application:
    name: reactive-book-client

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    shutdown:
      enabled: true   
info:
  build:
      artifactId: '@project.artifact@'
      groupId: '@project.groupId@'
  java:
    version: 8.0   
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

